# FECHOU O QUADRADO

Serão dois participantes e o objetivo do jogo é ver quem fecha  quadrado primeiro. 

## O JOGO 

In [ ]:
#### primeiro é definido o nome dos jogadores
jogador_1 = print("Quem vai jogar primeiro?")
jogador_1 = input()
print("Olá, " + jogador_1 +". Bem vindo(a) ao FECHOU O QUADRADO!" )

jogador_2 = print("e agora, quem é o 2°?")
jogador_2 = input()
print("Olá, " + jogador_2 +". Bem vindo(a) ao FECHOU O QUADRADO também!")

#depois é definido o  tabuleiro
print("Veja como é esse tabuleiro")
import numpy as np
lista = np.arange(0, 25).reshape(5, 5)
print(lista)
matriz = ["A1","X1","Y1","Z1","K1",
          "A2","X2","Y2","Z2","K2",
          "A3","X3","Y3","Z3","K3",
          "A4","X4","Y4","Z4","K4",
          "A5","X5","Y5","Z5","K5"]

print("Na horizontal temos A, X, Y, Z e K e na vertical os números de 1 a 5")

#para o funcionamento do jogo usamos 2 listas para cada jogador
lista_jogador_1 = []
count_1 = 0
lista_jogador_2 = []
count_2 = 0

#o primeiro jogador tem uma mensagem personalizada
print (jogador_1 + ", você começa!")
print ("escolha um elemento da matriz:")
print (matriz)
comand_1 = input()
lista_jogador_1.append(comand_1)
matriz.remove(comand_1)

#depois um looping foi criado para passar automaticamente do jogador 1 para o 2 até que acabe o jogo
while len(matriz) > 10:
    
    print (jogador_2 + ", agora é você!")
    print ("escolha um elemento da matriz:")
    print (matriz)
    comand_2 = input()
    lista_jogador_2.append(comand_2)
    matriz.remove(comand_2)
    
    print (jogador_1 + ", sua vez!")
    print ("escolha um elemento da matriz:")
    print (matriz)
    comand_1 = input()
    lista_jogador_1.append(comand_1)
    matriz.remove(comand_1)

#agora a contagem dos pontos do jogador 1
if "A1" and "X1" and "A2" and "X2" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "A2" and "X2" and "A3" and "X3" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "A3" and "X3" and "A4" and "X4" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "A4" and "X4" and "A5" and "X5" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "X1" and "Y1" and "X2" and "Y2" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "X2" and "Y2" and "X3" and "Y3" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "X3" and "Y3" and "X4" and "Y4" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "X4" and "Y4" and "X5" and "Y5" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "Y1" and "Z1" and "Y2" and "Z2" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "Y2" and "Z2" and "Y3" and "Z3" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "Y3" and "Z3" and "Y4" and "Z4" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "Y4" and "Z4" and "Y5" and "Z5" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "Z1" and "K1" and "Z2" and "K2" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "Z2" and "K2" and "Z3" and "K3" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "Z3" and "K3" and "Z4" and "K4" in lista_jogador_1:
    count_1 +=1
print(count_1)
if "Z4" and "K4" and "Z5" and "K5" in lista_jogador_1:
    count_1 +=1
print(count_1)

#agora a contagem dos pontos do jogador 2
if "A1" and "X1" and "A2" and "X2" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "A2" and "X2" and "A3" and "X3" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "A3" and "X3" and "A4" and "X4" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "A4" and "X4" and "A5" and "X5" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "X1" and "Y1" and "X2" and "Y2" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "X2" and "Y2" and "X3" and "Y3" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "X3" and "Y3" and "X4" and "Y4" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "X4" and "Y4" and "X5" and "Y5" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "Y1" and "Z1" and "Y2" and "Z2" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "Y2" and "Z2" and "Y3" and "Z3" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "Y3" and "Z3" and "Y4" and "Z4" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "Y4" and "Z4" and "Y5" and "Z5" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "Z1" and "K1" and "Z2" and "K2" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "Z2" and "K2" and "Z3" and "K3" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "Z3" and "K3" and "Z4" and "K4" in lista_jogador_2:
    count_2 +=1
print(count_2)
if "Z4" and "K4" and "Z5" and "K5" in lista_jogador_2:
    count_2 +=1
print(count_2)

if count_1 > count_2:
    Print("Boa " + jogador_1 + ", voce ganhou!")
elif count_1 < count_2:
    print("Boa " + jogador_2 + ", voce ganhou!")
else:
    Print("Jogo empatado")
    
    

Quem vai jogar primeiro?
Giuliana
Olá, Giuliana. Bem vindo(a) ao FECHOU O QUADRADO!
e agora, quem é o 2°?
Darua
Olá, Darua. Bem vindo(a) ao FECHOU O QUADRADO também!
Veja como é esse tabuleiro
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Na horizontal temos A, X, Y, Z e K e na vertical os números de 1 a 5
Giuliana, você começa!
escolha um elemento da matriz:
['A1', 'X1', 'Y1', 'Z1', 'K1', 'A2', 'X2', 'Y2', 'Z2', 'K2', 'A3', 'X3', 'Y3', 'Z3', 'K3', 'A4', 'X4', 'Y4', 'Z4', 'K4', 'A5', 'X5', 'Y5', 'Z5', 'K5']
A1
Darua, agora é você!
escolha um elemento da matriz:
['X1', 'Y1', 'Z1', 'K1', 'A2', 'X2', 'Y2', 'Z2', 'K2', 'A3', 'X3', 'Y3', 'Z3', 'K3', 'A4', 'X4', 'Y4', 'Z4', 'K4', 'A5', 'X5', 'Y5', 'Z5', 'K5']
Y3
Giuliana, sua vez!
escolha um elemento da matriz:
['X1', 'Y1', 'Z1', 'K1', 'A2', 'X2', 'Y2', 'Z2', 'K2', 'A3', 'X3', 'Z3', 'K3', 'A4', 'X4', 'Y4', 'Z4', 'K4', 'A5', 'X5', 'Y5', 'Z5', 'K5']
X1
Darua, agora é você!
escolha um elemento da mat

# Passo a passo do Game

## Passo 1 - Definir jogador


## Passo 2 - Montar quadrantes com 25 pontos

## Passo 3 - Definir as possibilidades de ação de cada ponto

## Passo 4 - Registrar o movimento do Jogador

## Passo 5 - Identificar quando um ponto é feito

## Passo 6 - Placar do Jogador

## Passo 7 - Passar a vez para o jogador seguinte

## Passo 8 - Registrando a última jogada

## Passo 9 - Identificar jogador com mais pontos

## Passo 10 - Parabenizar o Jogador